### PR TITLE
Fixing the scaling issues with buttons and text

### PR DESCRIPTION
**Pull request by BrandonS09**
Getting os to determine constants for buttons and text scaling, Mac ppl pls test

### CODE REVIEW

**Comment by FriedLongJohns** [comment]
Works on Mac.
I assume it works on Windows, since that's what @BrandonS09 uses.
Need linux confirmation from @akpi816218

**Comment by FriedLongJohns** [comment]
However, we should write code to automatically shift all UI children elements before the first render frame so that all computers have the same numbers when placing elements, but they get autoscaled to their correct OSs' positions.

**Comment by ackledotdev** [comment]
> Works on Mac.
> I assume it works on Windows, since that's what @BrandonS09 uses.
> Need linux confirmation from @akpi816218 
will test and let you know

**Review by ackledotdev — COMMENTED** [review]
will test button placement on Linux later today, then update review to explicit approval assuming all is well

**Comment by ackledotdev** [comment]
Starting tests

**Review by ackledotdev — DISMISSED** [review]
UI spacing & scaling checks out on Linux (Ubuntu 24.04.1 LTS, Python v3.12)
copied values from Windows and edited to fit

**Review by FriedLongJohns — APPROVED** [review]
still works.

**Pull request merged**
