### PR TITLE
UI autoscaling

### PR DESCRIPTION
**Pull request by FriedLongJohns**
works.
need @BrandonS09 to send a screenshot to confirm but otherwise good enough

### CODE REVIEW

**Comment by BrandonS09** [comment]
I'm away from home rn, will send a SS as soon as I can

**Comment by ackledotdev** [comment]
will review later

**Comment by BrandonS09** [comment]
@FriedLongJohns I pulled, then ran `poetry install` and `poetry run app` now getting traceback on the fonts:
`Traceback (most recent call last):
  File "<string>", line 1, in <module>
0\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Brandon Shen\Documents\NASA-ADC-24\nadc2025\main.py", line 10, in <module>
    from nadc2025 import config
  File "C:\Users\Brandon Shen\Documents\NASA-ADC-24\nadc2025\config.py", line 9, in <module>
    FONTLIST = [file for file in os.listdir(ursina.application.fonts_folder) if file.endswith(".ttf") or file.endswith(".otf")]
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\Brandon Shen\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\nadc2025-xCl9I7aV-py3.12\\Scripts\\fonts'`
Screenshot 2024-11-02 202134

**Comment by BrandonS09** [comment]
> I'm away from home rn, will send a SS as soon as I can

SS on windows:

Screenshot 2024-11-02 202801

**Review by BrandonS09 — DISMISSED** [review]

**Review by BrandonS09 — APPROVED** [review]

**Comment by ackledotdev** [comment]
fixes #5

**Pull request merged**
