### PR TITLE
separate data loading into it's own file

### PR DESCRIPTION
**Pull request by FriedLongJohns**
data loading is done ASYNCHRNOUSLY -

you must use the data.wait_until_ready when grabbing calculated data points, but this realistically has no effect unless we begin to take full seconds to load all our data.

current loading order is 
0: raw (x,y,z, time-min, mass)
1: trajectory (vec3 list of all xyz points)
2: time (seconds, hours, percentage)

### CODE REVIEW

**Comment by BrandonS09** [comment]
Change your import statement to `from nadc2025 import libdata as data` for some reason, python doesn't like ur current import statement, at least that's how it is on windows, other than that, looks good

**Comment by FriedLongJohns** [comment]
how are you running the project?
that seems strange

**Comment by BrandonS09** [comment]
With poetry 
Screenshot 2024-10-31 231111

**Comment by FriedLongJohns** [comment]
fixed.

**Review by BrandonS09 — APPROVED** [review]

**Comment by FriedLongJohns** [comment]
image

**Pull request merged**
